# Generated by Django 4.2.1 on 2023-10-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUploading', '0002_customuser_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
